{
  "version": 0.0,
  "Resources": [
    {
      "TargetService": {
        "Type": "AWS::ECS::Service",
        "Properties": {
          "TaskDefinition": "arn:aws:ecs:us-east-1:811738710312:task-definition/strapi-task:225",
          "LoadBalancerInfo": {
            "ContainerName": "strapi-app",
            "ContainerPort": 1337
          }
        }
      }
    }
  ]
}